[package]
name = "sigstore_protobuf_specs_codegen"
version = "0.1.0"
authors = ["Sigstore Authors <sigstore-dev@googlegroups.com>"]
edition = "2021"
description = "Rust AOT codegen for sigstore protobuf-specs"
readme = "../README.md"
license-file = "../LICENSE"

[dependencies]
anyhow = "1.0.72"
glob = "0.3"
pbjson-build = "0.5.1"
prost-build = "0.11.9"
