FROM node:24@sha256:7f80506b8225bcce2ce8202b1026fcde8f0bfb716b1b833f20250d79d4463276 AS typescript-builder
RUN mkdir /app
COPY hack/package*.json /app
WORKDIR /app

# this flattens the node_modules in a way similar to the global install (which we'll (ab)use in a second)
RUN npm ci --install-strategy=shallow

# /usr/bin/env is called from ts-proto but not in distroless by default; we use busybox for this
FROM gcr.io/distroless/base-debian13:debug-nonroot@sha256:42bc6f19adf18acd9e17344170d400777e1da02540cf46e3c09e8afc9e18c703 AS env-source

FROM gcr.io/distroless/nodejs24-debian13:nonroot@sha256:5bee7069294b1d497978cc13e42f0f205398e97b0313269fdd0bb1bda14e09be

# node is installed in a non-default location in distroless
ENV PATH=$PATH:/nodejs/bin

COPY --from=typescript-builder /app/node_modules /usr/local/lib/node_modules
COPY --from=env-source /busybox/busybox /usr/bin/env
COPY --from=protoc-base:typescript /protobuf/bin/protoc /usr/local/bin/
COPY --from=protoc-base:typescript /protobuf/include/google /opt/include/google
COPY --from=protoc-base:typescript /googleapis /googleapis

ENTRYPOINT ["/usr/local/bin/protoc", "--plugin=/usr/local/lib/node_modules/ts-proto/protoc-gen-ts_proto" ]
