FROM python:3.13.2-alpine@sha256:323a717dc4a010fee21e3f1aac738ee10bb485de4e7593ce242b36ee48d6b352

RUN pip3 install --upgrade --quiet pip

# the specific versions of python protobuf tools are in hack/dev-requirements.txt so that Dependabot can bump them for updates
ADD hack/dev-requirements.txt .

RUN pip3 install -r dev-requirements.txt

COPY --from=protoc-base:python /protobuf/bin/protoc /usr/local/bin/
COPY --from=protoc-base:python /protobuf/include/google /opt/include/google
COPY --from=protoc-base:python /googleapis /googleapis

ENTRYPOINT ["/usr/local/bin/protoc" ]
