FROM python:3.14.2-alpine@sha256:31da4cb527055e4e3d7e9e006dffe9329f84ebea79eaca0a1f1c27ce61e40ca5

RUN pip3 install --upgrade --quiet pip

# the specific versions of python protobuf tools are in hack/dev-requirements.txt so that Dependabot can bump them for updates
ADD hack/dev-requirements.txt .

RUN pip3 install -r dev-requirements.txt

COPY --from=protoc-base:python /protobuf/bin/protoc /usr/local/bin/
COPY --from=protoc-base:python /protobuf/include/google /opt/include/google
COPY --from=protoc-base:python /googleapis /googleapis

ENTRYPOINT ["/usr/local/bin/protoc" ]
