FROM node:26@sha256:b46a10d964ad15136ebdf9012142131481caa0697d7a4d4eafe4bbabd818f876 AS typescript-builder
RUN mkdir /app
COPY hack/package*.json /app
WORKDIR /app

# this flattens the node_modules in a way similar to the global install (which we'll (ab)use in a second)
RUN npm ci --install-strategy=shallow

# /usr/bin/env is called from ts-proto but not in distroless by default; we use busybox for this
FROM gcr.io/distroless/base-debian13:debug-nonroot@sha256:e1fc4be8eca9f72c5e45378b91c864dc4d5b9db15daaa9bb943411368699d74a AS env-source

FROM gcr.io/distroless/nodejs24-debian13:nonroot@sha256:ed5e65a1036b505c9e5abf0d0412ce0f70be1b812630bbbbaf49ce47edc7a513

# node is installed in a non-default location in distroless
ENV PATH=$PATH:/nodejs/bin

COPY --from=typescript-builder /app/node_modules /usr/local/lib/node_modules
COPY --from=env-source /busybox/busybox /usr/bin/env
COPY --from=protoc-base:typescript /protobuf/bin/protoc /usr/local/bin/
COPY --from=protoc-base:typescript /protobuf/include/google /opt/include/google
COPY --from=protoc-base:typescript /googleapis /googleapis

ENTRYPOINT ["/usr/local/bin/protoc", "--plugin=/usr/local/lib/node_modules/ts-proto/protoc-gen-ts_proto", "--ts_proto_opt=protoJsonFormat=false"]
