FROM rust:1.95.0@sha256:a9cfb755b33f5bb872610cbdb25da61f527416b28fc9c052bbce4bef93e7799a

COPY --from=protoc-base:rust /protobuf/bin/protoc /usr/local/bin/
COPY --from=protoc-base:rust /protobuf/include/google /opt/include/google
COPY --from=protoc-base:rust /googleapis /googleapis

# this is not protoc because we will call Rust's prost crate to do the compilation
ENTRYPOINT [ "/bin/bash" ]
