FROM python:3.14.6-alpine@sha256:26730869004e2b9c4b9ad09cab8625e81d256d1ce97e72df5520e806b1709f92

# the specific versions of python protobuf tools are in hack/dev-requirements.txt so that Dependabot can bump them for updates
ADD hack/dev-requirements.txt .

RUN pip3 install --quiet -r dev-requirements.txt

COPY --from=protoc-base:python /protobuf/bin/protoc /usr/local/bin/
COPY --from=protoc-base:python /protobuf/include/google /opt/include/google
COPY --from=protoc-base:python /googleapis /googleapis

ENTRYPOINT ["/usr/local/bin/protoc" ]
