FROM rust:1.94.1@sha256:f2a0f2b3529c9bbbf5479d131611451a3cc3956d9a11374d6d4ba96f059c1dce

COPY --from=protoc-base:rust /protobuf/bin/protoc /usr/local/bin/
COPY --from=protoc-base:rust /protobuf/include/google /opt/include/google
COPY --from=protoc-base:rust /googleapis /googleapis

# this is not protoc because we will call Rust's prost crate to do the compilation
ENTRYPOINT [ "/bin/bash" ]
