FROM rust:1.91.1@sha256:ad8c72c693b517ed60c930839daed91a5696fa6118f031d888cd0b7055a921a3

COPY --from=protoc-base:rust /protobuf/bin/protoc /usr/local/bin/
COPY --from=protoc-base:rust /protobuf/include/google /opt/include/google
COPY --from=protoc-base:rust /googleapis /googleapis

# this is not protoc because we will call Rust's prost crate to do the compilation
ENTRYPOINT [ "/bin/bash" ]
