FROM node:24@sha256:dd5c5e4d0a67471a683116483409d1e46605a79521b000c668cff29df06efd51 AS typescript-builder
RUN mkdir /app
COPY hack/package*.json /app
WORKDIR /app

# this flattens the node_modules in a way similar to the global install (which we'll (ab)use in a second)
RUN npm ci --install-strategy=shallow

# /usr/bin/env is called from ts-proto but not in distroless by default; we use busybox for this
FROM gcr.io/distroless/base-debian12:debug-nonroot@sha256:20bc1021b26cbc67b9b40f8df10d97a06287312b19a5ae86092cb33d0fcd8ab5 AS env-source

FROM gcr.io/distroless/nodejs22-debian12:nonroot@sha256:2a8c8af8bf7046d71efccaf1226e491f2ef934f3079dca9ad8ebbf36551f7fc5

# node is installed in a non-default location in distroless
ENV PATH=$PATH:/nodejs/bin

COPY --from=typescript-builder /app/node_modules /usr/local/lib/node_modules
COPY --from=env-source /busybox/busybox /usr/bin/env
COPY --from=protoc-base:typescript /protobuf/bin/protoc /usr/local/bin/
COPY --from=protoc-base:typescript /protobuf/include/google /opt/include/google
COPY --from=protoc-base:typescript /googleapis /googleapis

ENTRYPOINT ["/usr/local/bin/protoc", "--plugin=/usr/local/lib/node_modules/ts-proto/protoc-gen-ts_proto" ]
