# This Dockerfile exists to allow Dependabot to watch Homebrew builds of protobuf for triggering updates
# We don't actually use the content of this image in the repo, as this is a dynamically linked version of protoc
FROM ghcr.io/homebrew/core/protobuf:33.4@sha256:68f29c2b7ba1806379bd140964f16233c6a2dbffa6086b0531f36d2803105a80
