on:
  push:
    tags:
      - 'release/python/v*'

permissions: {}

name: release Python package

jobs:
  pypi:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # required for trusted publishing to PyPI

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: "3.x"

    - name: build
      run: |
        cd gen/pb-python/
        make package

    - name: publish
      uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # v1.14.1
      with:
        packages-dir: gen/pb-python/dist/
