on:
  push:
    tags:
      - 'release/python/v*'

permissions: {}

name: release Python package

jobs:
  pypi:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # required for trusted publishing to PyPI

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: "3.x"

    - name: build
      run: |
        cd gen/pb-python/
        make package

    - name: publish
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
      with:
        packages-dir: gen/pb-python/dist/
